### ISSUE TITLE
Need amount paid

### ISSUE THREAD

**Issue by elaynepelz** [ChicagoWorldcon/wellington#153]
In order to perform upgrades on site the amount a member paid when they joined is required.  A separate field with a figure is needed.  

If the member has already upgraded, then that figure is needed instead.

Especially needed when daily memberships start getting sold.

**Comment by offbyone** [comment]
Per some of our side conversations, this cannot come entirely from wellington, since it does not have complete payment information. If I'm wrong in that regard, feel free to re-open this.
