### ISSUE TITLE
Hugo packet access requires an actual charge, rather than a membership whose status is "paid"

### ISSUE THREAD

**Issue by offbyone** [ChicagoWorldcon/wellington#154]
This is a side effect of the cart + membership transfers. The query in the `check_access!` method in the hugo packet controller is checking for successful charges, but that only applies when the user used our payment processor. Comped memberships won't have this, for example, and nor will memberships whose rights are transferred, necessarily.

This should affect only a subset of users, but it must be fixed.

**Comment by katjonzz** [comment]
Possibly related - we've had two reports of people who have made the initial payment on a payment plan of at least $50 (and thus have a Supporting membership), who cannot access their online ballots. You've probably already seen these coming in to Registration from Terry.
