### ISSUE TITLE
That pesky old shopping cart

### ISSUE THREAD

**Issue by Lasiorhine** [ChicagoWorldcon/wellington#47]
Creating an actual story for this.  Because we carried this over from Gitlab, but somehow we didn't copy the story.

Previous branches, for reference, include:
[Chris's original WIP branch](https://github.com/ChicagoWorldcon/wellington/tree/107-add-shopping-cart)
and
[A bashing branch for the branch above.](https://github.com/ChicagoWorldcon/wellington/tree/107-a-veg-bashes-cart)

**Comment by offbyone** [comment]
Requirements (as I am aware of them):

* purchase multiple memberships in a single Stripe/CC transaction
   * each membership should be fully filled out at the point of purchase
* allow the addition of non-membership purchase items, such as fan fund donations or t-shirts (so, both non-physical and possibly product-base purchases)

Optional:

* allow the user to indicate that they are paying for the cart by cheque instead
   * the operator/support user who receives the cheque then needs to mark the whole cart as paid.
